services:

  px4_lab:

    image: fabiodrone71/px4-ros2-lab:humble

    container_name: px4_lab

    network_mode: host

    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
      - LIBGL_ALWAYS_SOFTWARE=1

    volumes:
      - ./PX4-Autopilot:/workspace/PX4-Autopilot
      - ./ros2_ws:/workspace/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    working_dir: /workspace

    stdin_open: true

    tty: true

    command: bash
